### ISSUE TITLE
Release bubba3-kernel for 5.10.149-1 which addresses DSA-5257

### ISSUE THREAD

**Issue by fredrikjonson** [Excito/kernel-5.10#1]
It would be neat if bubba3-kernel was updated to linux 5.10.149-1, which includes several wifi security fixes.

https://www.debian.org/security/2022/dsa-5257

Thanks! :)

**Comment by MouettE-SC** [comment]
Hello. Thanks for the issue, I must admit I completely missed it. I just released version 5.10.177-1 which fixes this CVE (and add wireguard support). Thanks for your issue and don't hesitate if you see anything worth of upgrading the kernel.
