### ISSUE TITLE
Wireguard support for 5.10.117-1 - missing module

### ISSUE THREAD

**Issue by Stan-Tastic** [Excito/kernel-5.10#2]
Since I moved my entire VPN to wireguard, I wanted my B3 to take part in the fun as well. Sadly, though I can install Wireguard, its module is missing from kernel:

```
modprobe wireguard
modprobe: FATAL: Module wireguard not found in directory /lib/modules/5.10.117-1
```

I hoped I can build from source (according to Wireguard homepage), but I can't download headers:

```
# apt-get install libelf-dev linux-headers-$(uname -r) build-essential pkg-config
[...]
E: Can't find package linux-headers-5.10.117-1
```

Can you please include Wireguard support in the kernel?

**Comment by MouettE-SC** [comment]
Hello,

This is actually very relevant, I will release a new version with wireguard added. It's gonna take a few days, in the mean time, you can try installing kernel headers with the following command : `apt install bubba3-kernel-headers-armel` and manually compile (I'm curious to see if it works).

**Comment by MouettE-SC** [comment]
I tried to compile with headers, but no luck, the headers package is missing files. Anyway the new version is currently compiling, I should be able to release it tomorrow.

**Comment by MouettE-SC** [comment]
Hello, sorry for the delay. Version 5.10.177-1 has been pushed to the repository with wireguard module added. Thanks and let me know if it works !
